language: node_js
node_js:
- 8
- 7
- 6
cache: npm
jobs:
  include:
  - stage: github release
    node_js: '6'
    deploy:
      provider: releases
      api_key:
        secure: ls/IjZdRpFZlEQsZrsmXn7h7QTZuM8x4gZq3r75sOyTWcmKgZLN27hYCtk8SPcuNbt+ZA3otQEQJvDuGTCAwtbU4lxQjfXswP9M/om01hf3J7uTcjtol4XOsmBFqMCktW94pVH4U7Q18IHeP5JBnlfLzAY/YifRKKNWNrsI6bbnfcGgsFJYvICwKL5LEj7bxtJk156lBBJm9TscMX48BFsUBvnCNTDEBYNaaGkoCz6DPM0Da7QPF5exHcNiiF9SoR60WeGI1q+MdZyE+1AG0VpUp7sMxJafXSBbgYquPEZmG9ScZbkVyWP7ps3sgkqDkxtH4kNe9zF4PySRYfxYKJ03ECwbSmj9gxsIc8o2zhrLFinmHydLxoOEh5EygB2euekgMhoEKL0kA8bteaaqmD+3sna8MbXG4HhvIrEAspNtOFZyUm/SmgvXXxaKiDtwTw/5CvPCc7VH51NuC5QZi0UehLzatDpDNsj/ffMwDp5F4SBIZgUUmmIWfnAODNGwSwBKxdPVS3etkTeiBxerw2uzC6qjNW1QJyb9s+iU3rC59IEAuq6u4ymv3caDIHLnJbCMHRHQoIbq86oErqb8DhH6KrTlBnwlGBpUVhdpYMt0QX2Uncu9uHMBZ2CQNZ819PJa4QWvc1Ixoj3auKqvoMfPNQFOskMWnrnxkOokyPZg=
      skip_cleanup: true
      on:
        tags: true
  - stage: npm release
    node_js: '6'
    deploy:
      provider: npm
      email: fabiojose@gmail.com
      api_key:
        secure: o5aF53FTPUSiJBbCZ/anBWQCgEJCctpxuTgGJbO1NpiheOM/xENiSmv+n2a5sGrhhqT0h7k15mE/ZgtL8TnM+45AHOg3EGez5JoR1XMIXnSeCno1GFK4waHDcEn3eLW9P35r1S5/RMTqbEUvqpyK/fzVZ4ecyh9t7dVvJV8MyQGo+r+oO3SLYEIt7YC6vZRh+dV3cK8jr7MHkHmQfZ6tZrALMKsj6QNTUtmk+IU52WHi4oe1iPuypS5dlaVdmanX7ZRtC7gR0Dko2/wja+DPOAKgG/S0aS794cxal7P5k/K34mvqT8iaCl4vN5uIcRsipgsprIahk2G2NgnIVCetBda9LhpMNUdn3j+v4T0lx3jiqP1eq01nk8YFpTV4Xz9VlYHK/E6NYQhUmd7N6WO9vXmOEDGBvWrDfQ1QMx+/TM9r3vzK9ps3sjkDFaAtJ2ZQ0pvFMEQTaLKak24ntWltSWZKvxdjYnS+bcfyIQQGagvqgZsnkKzeudO9N9Atp4OGcst9CAvvykDsfmLlARAiyvpuDVyUivuaOlCB9J7VBt1sbBfsiHpnJcSsMVz1OMRX5EGewbla530guoePhjTUDVit3NyUMz3ZQQTN9VSK3tA+NLyR0Ex8Oel+byHJDYyf+36GCDvoXagaPUVk5M5BINiCw2IWhxDgRGrcEp9JIUI=
      skip_cleanup: true
      on:
        tags: true
env:
  global:
    secure: GgLsminwitZCtFwRkijoF03uz0+jA+jayrWyvkFfipND8S7KkmcY6iqBjBkA/ZNkvh2jgwD3fG7Jp6f795Oyb6oq8u/xF7h446YcG4FPye1v6abWhKLaOQrcTca++xl6Ph6sHRRwaV2dw/UIRRHikJWZEIKS2jgAkQ1dW7srMJhIWTIegDYYpj3c1Ri2wL5S9799zyO/c12JLpawxQvzhEG2YyYkdEI0H/9HsUezoBrCZdxjVb/LAa0nUTmQiAfX4CYRHidU4QCbznQhHWFdGr/9wKvy1dyCxAWLosWSy+mIq3teeCJ80c/Yi+yEv96tg5wL75shfYzx4JMSL6YIyfF6OrbAM0jYGIMJdf/UEG1TKNpRnIqugnCJbdjZpn6mavrayjnaq9KSc7wgXBXox5jucfWLDfV2LZ18qfqHIeubIT7X69k8P5M4z4MU3YR3mqiZtEy6CPi+h0ReMLheFKemAmHWSL4zV1YfBRFVyFP0LM4Qsi4UVtCJQUHwvjNcO2ZUXLe6OzqXN987JKwTOyecmn9s/24UDofBxuMqTWYTssKPI0bHpOiWCqd5ml9Uz1/5o6bjGhvbJjv1K/0xWS2PoWim/RSnNTNi+en+GgEKuaDZkCktHVOKg7xkpsW0DvtcpwVQRdyXUN1s2h+EHgSBuoeAo4fhbXRUVsu5zuY=
script: npm run coverage
